# Generated by Django 5.0.6 on 2025-10-29 10:15

import django.utils.timezone
import sharing_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sharing_app.models.user_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('share_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
