# Generated by Django 5.0.6 on 2025-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='shared_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='shared_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
