# Generated by Django 5.0.6 on 2025-11-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0003_sharedfile_shared_expiry_sharedfile_shared_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
