# Generated by Django 5.2.4 on 2025-11-09 11:01

import sharing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0005_folder_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=sharing_app.models.user_upload_path),
        ),
    ]
