# Generated by Django 5.0.6 on 2025-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0007_file_deleted_at_file_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='max_share_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
