# Generated by Django 5.2.4 on 2025-11-11 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0008_sharedfile_max_share_limit_sharedfile_share_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sharedfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='file',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='sharing_app.folder'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
