# Generated by Django 5.2.4 on 2025-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0009_alter_file_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
