# Generated by Django 5.2.4 on 2025-11-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0010_file_original_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='sharing_app.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sharing_app.folder'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to='shared/'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='max_share_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'parent', 'name')},
        ),
    ]
