# Generated by Django 5.2.4 on 2025-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0011_remove_file_folder_name_alter_file_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
