# Generated by Django 5.2.4 on 2025-11-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0012_file_updated_at_folder_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
