# Generated by Django 5.2.4 on 2025-11-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0014_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
