# Generated by Django 5.0.6 on 2025-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0015_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
